server:
  display-name: feign-service
  port: 8180
  contextPath: /feign-service

spring:
  profiles:
    active: dev
  application:
    name: ${server.display-name}

management:
  security:
    enabled: false

# 访问安全策略关闭
security:
  basic:
    enabled: true #开启认证
  user:
    name: guest
    password: guest

# DataSource
fegin-service:
  dataSource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/boot

# eureka
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/eureka  #注册 中心已经开启认证
  instance:
    hostname: localhost
    ip-address: localhost
    non-secure-port: ${server.port}
    instance-id: feign-service:${eureka.instance.ip-address}:${server.port}:@project.version@
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10