server:
  display-name: boot-service
  port: 8080
  contextPath: /boot-service

spring:
  profiles:
    active: dev
  application:
    name: ${server.display-name}

management:
  security:
    enabled: false

# 访问安全策略关闭
security:
  basic:
    enabled: false

dcommons-token:
  cookieName: boot_jwt
  secret: xxx
  expSeconds: 86400
  refreshIntervalSeconds: 900

# DataSource
boot-service:
  dataSource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/boot

