# contextPath 目的在于使用boot的访问url路径没有项目层，添加后访问路径带有项目层
server:
  display-name: boot-service
  port: 8081
  contextPath: /boot-service

spring:
  profiles:
    active: dev
  application:
    name: ${server.display-name}

management:
  security:
    enabled: false

security:
  basic:
    enabled: true #开启认证
  user:
    name: guest
    password: guest

dcommons-token:
  cookieName: boot_jwt
  secret: xxx
  expSeconds: 86400
  refreshIntervalSeconds: 900

# DataSource
boot-service:
  dataSource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/boot
  rest:
    username: guest
    password: guest

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka/  #注册 中心已经开启认证 如果eureka-server配置了contextPath，此处需要在域名和eureka之间加上contextPath值
  instance:
    hostname: localhost
    ip-address: localhost
    non-secure-port: ${server.port}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}:@project.version@
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: ${endpoints.info.path}
    health-check-url-path: ${endpoints.health.path}

endpoints:
  sensitive: false
  shutdown:
    enabled: true
  info:
    path: ${server.contextPath}/info
  health:
    path: ${server.contextPath}/health
# feigin调用接口权限使用basic auth模式
feign-service:
  auth:
    username: guest
    password: guest
