server:
  display-name: boot-web
  port: 8080
  contextPath: /boot-web

spring:
  profiles:
    active: dev
  application:
    name: ${server.display-name}

management:
  security:
    enabled: false

# 访问安全策略关闭
security:
  basic:
    enabled: false

